# Minimal Makefile for Sphinx documentation

SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = source
BUILDDIR      = build

.PHONY: help Makefile html linkcheck clean

help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  html      to make standalone HTML files"
	@echo "  linkcheck to check all external links for integrity"
	@echo "  clean     to remove build directory"

html:
	@echo "HTML documentation build not yet implemented"
	@echo "Phase 1 complete - documentation will be added in Phase 6"
	@mkdir -p $(BUILDDIR)/html
	@echo "<html><body><h1>Neurosheaf Documentation</h1><p>Documentation will be available in Phase 6</p></body></html>" > $(BUILDDIR)/html/index.html

linkcheck:
	@echo "Link checking not yet implemented"
	@echo "Phase 1 complete - link checking will be added in Phase 6"

clean:
	rm -rf $(BUILDDIR)

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@echo "Documentation target '$@' not yet implemented"
	@echo "Phase 1 complete - full documentation will be added in Phase 6"